/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componentes;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Islas García César Fernando
 */
public class BotonCambiarPanel extends javax.swing.JPanel {

    private String texto;
    private String srcImage;
    private int tamanioFuente;

    private JPanel panelReferenciado;
    private interfaces.IContenedor contenedor;

    public BotonCambiarPanel(String texto, String srcImage, JPanel panelReferenciado, interfaces.IContenedor contenedor) {
        this.texto = texto;
        this.srcImage = srcImage;
        this.panelReferenciado = panelReferenciado;
        this.contenedor = contenedor;

        initComponents();

        lblTxt.setText(texto);
        lblIcon.setIcon(new ImageIcon(getClass().getResource(srcImage)));

        revalidate();
        repaint();
    }

    public BotonCambiarPanel(String texto, int tamanioFuente, JPanel panelReferenciado, interfaces.IContenedor contenedor) {
        this.texto = texto;
        this.tamanioFuente = tamanioFuente;
        this.panelReferenciado = panelReferenciado;
        this.contenedor = contenedor;

        initComponents();

        lblTxt.setFont(new Font("Poppins SemiBold", Font.PLAIN, tamanioFuente));
        lblTxt.setText(texto);
        
        lblIcon.setVisible(false);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIcon = new javax.swing.JLabel();
        lblTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 209, 220));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(400, 15));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTxt.setBackground(new java.awt.Color(2, 54, 94));
        lblTxt.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        lblTxt.setForeground(new java.awt.Color(2, 54, 94));
        lblTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTxt.setText("lblTxt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        contenedor.cambiarPanel(panelReferenciado);
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        setBackground(new Color(255, 255, 255));
        revalidate();
        repaint();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        setBackground(new Color(190, 209, 220));
        revalidate();
        repaint();
    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTxt;
    // End of variables declaration//GEN-END:variables
}
